adjektive1 = input("Indsæt et adjektiv: ")
noun = input("Indsæt et navneord: ")
adjektive2 = input("Indsæt et adjektiv: ")
verb = input("Indsæt et udsagsord: ")
adjektive3 = input("Indsæt et adjektiv: ")

print(f"I dag gik jeg i en {adjektive1} zoologisk have.")
print(f"I en indhegning, så jeg {noun}")
print(f"{noun} var {adjektive2} og {verb}")
print(f"Jeg var {adjektive3}")
